
development:
  adapter: mysql2
  encoding: utf8
  database: conflict_reporting_development
  pool: 5
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  database: conflict_reporting_test
  pool: 5
  username: root
  password: 

production:
  adapter: mysql2
  encoding: utf8
  database: conflict_reporting
  pool: 5
  username: root
  password: 
