production:
  url: http://nuntium.instedd.org
  account: balkumar
  application: Sajhedari
  channel: Sajhedari_Channels
  password: Sajhedari #password application

development:
  url: http://nuntium.instedd.org
  account: balkumar
  application: Sajhedari
  channel: Sajhedari_Channels
  password: Sajhedari #password application

testing:
  url: http://nuntium.instedd.org
  account: balkumar
  application: Sajhedari
  channel: Sajhedari_Channels
  password: Sajhedari #password application